SELECT FOOD_ORDER.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, SUM(FOOD_ORDER.AMOUNT)*FOOD_PRODUCT.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT INNER JOIN FOOD_ORDER ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE FOOD_ORDER.PRODUCE_DATE LIKE '2022-05%'
GROUP BY FOOD_ORDER.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FOOD_ORDER.PRODUCT_ID

