SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P RIGHT JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID = (SELECT MEMBER_ID AS CNT FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(REVIEW_ID) DESC LIMIT 1)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT;