WITH REVIEW_COUNT AS (SELECT MEMBER_ID, COUNT(*) AS COUNT
FROM REST_REVIEW
GROUP BY MEMBER_ID)


SELECT MEMBER_PROFILE.MEMBER_NAME, REST_REVIEW.REVIEW_TEXT, DATE_FORMAT(REST_REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW JOIN MEMBER_PROFILE ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID JOIN REVIEW_COUNT ON REST_REVIEW.MEMBER_ID = REVIEW_COUNT.MEMBER_ID
WHERE REVIEW_COUNT.COUNT = (SELECT MAX(COUNT) FROM REVIEW_COUNT)
ORDER BY REST_REVIEW.REVIEW_DATE, REST_REVIEW.REVIEW_TEXT
