SELECT DISTINCT CRCRH.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CRCC RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE MONTH(CRCRH.START_DATE) = 10 AND CAR_TYPE='세단'
ORDER BY CRCRH.CAR_ID DESC